# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "1pxrxznp0cv1gn6j2z0jglik39gqpdr9y4v1ha543jcyimdnxbfi";
    aarch64-linux = "0kgdpgl397qpd8xg9sz4adrzmlvfkhygr1yf7c8nfcz6sh5iqpjx";
    x86_64-darwin = "0fnw0hr41xl7167fxkvdcz6b2rcg5bwsqzaz88fvvz04kh0dzzzz";
    aarch64-darwin = "0w2yml3sbnn344817cc1jn3zqklpc990ii434f8yz2sbhzk8fxqv";
  };

  urlMap = {
    x86_64-linux = "https://github.com/AppleGamer22/cocainate/releases/download/v1.1.3/cocainate_1.1.3_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/AppleGamer22/cocainate/releases/download/v1.1.3/cocainate_1.1.3_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/AppleGamer22/cocainate/releases/download/v1.1.3/cocainate_1.1.3_mac_amd64.tar.gz";
    aarch64-darwin = "https://github.com/AppleGamer22/cocainate/releases/download/v1.1.3/cocainate_1.1.3_mac_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "cocainate";
  version = "1.1.3";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./cocainate $out/bin/cocainate
    installManPage ./cocainate.1
    installShellCompletion ./cocainate.*sh
  '';

  system = system;

  meta = {
    description = "Cross-platform caffeinate alternative.";
    homepage = "https://github.com/AppleGamer22/cocainate";
    license = lib.licenses.gpl3Only;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
