# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "0prdb7yhwkzsqqqc2qcaisphw2j12aqhm09bbzlfylhc24ywjc7b";
    aarch64-linux = "1vyngyag7y4vwnmzv7gs4fg6f3k1f7f77fdlg7l0yq2hri8kxcdw";
    x86_64-darwin = "0ky0jhqkdxk2jjpib4x5w7dkry4xlm06wm99az2b1n6b7w5cm63s";
    aarch64-darwin = "0brqqq42y3kbafs5hj3yyl673pv2mdgyfj0djcc2vvkcxbsgkgdf";
  };

  urlMap = {
    x86_64-linux = "https://github.com/AppleGamer22/cocainate/releases/download/v1.1.2/cocainate_1.1.2_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/AppleGamer22/cocainate/releases/download/v1.1.2/cocainate_1.1.2_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/AppleGamer22/cocainate/releases/download/v1.1.2/cocainate_1.1.2_mac_amd64.tar.gz";
    aarch64-darwin = "https://github.com/AppleGamer22/cocainate/releases/download/v1.1.2/cocainate_1.1.2_mac_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "cocainate";
  version = "1.1.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./cocainate $out/bin/cocainate
    installManPage ./cocainate.1
    installShellCompletion ./cocainate.*sh
  '';

  system = system;

  meta = {
    description = "Cross-platform caffeinate alternative.";
    homepage = "https://github.com/AppleGamer22/cocainate";
    license = lib.licenses.gpl3Only;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
