# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "1zhl2rzj6f4v312gfzhaq4s7gaxm6632k2c9d30lxs1jfxw6v5p1";
    aarch64-linux = "0wda9y4gnsw80gxz80hh1b1s962mjqyinhbj7n0wdpfvr6b1sr5p";
    x86_64-darwin = "00r0g5g57kr0w6scipyd4dxk0b8d48b8qdg2i35178n4s4c9qjh3";
    aarch64-darwin = "0vz5qc6bg776pkbpf7kf57ypfbaqa9m53cy5x4pw85skdxzis9as";
  };

  urlMap = {
    x86_64-linux = "https://github.com/AppleGamer22/cocainate/releases/download/v1.1.4/cocainate_1.1.4_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/AppleGamer22/cocainate/releases/download/v1.1.4/cocainate_1.1.4_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/AppleGamer22/cocainate/releases/download/v1.1.4/cocainate_1.1.4_mac_amd64.tar.gz";
    aarch64-darwin = "https://github.com/AppleGamer22/cocainate/releases/download/v1.1.4/cocainate_1.1.4_mac_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "cocainate";
  version = "1.1.4";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./cocainate $out/bin/cocainate
    installManPage ./cocainate.1
    installShellCompletion ./cocainate.*sh
  '';

  system = system;

  meta = {
    description = "Cross-platform caffeinate alternative.";
    homepage = "https://github.com/AppleGamer22/cocainate";
    license = lib.licenses.gpl3Only;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
